export default {
    LOAD_MAP: 'LOAD_MAP',
    CHANGED_MAP: 'CHANGED_MAP',
    START_GAME: 'START_GAME',

    MOVE_LEFT: 'MOVE_LEFT',
    MOVE_RIGHT: 'MOVE_RIGHT',
    MOVE_DOWN: 'MOVE_DOWN',
    MOVE_UP: 'MOVE_UP',

    GOLD_TO_PLAYER: 'GOLD_TO_PLAYER',
    SILVER_TO_PLAYER: 'SILVER_TO_PLAYER',
    BOMB_TO_PLAYER: 'BOMB_TO_PLAYER',

    BLAST: 'BLAST',
    FINISH: 'FINISH',

    MAX_BOMB: 3,
    MAX_COUNT: 6,
    MIN_COUNT: 3,

    LEFT: 65,
    RIGHT: 68,
    UP: 87,
    DOWN: 83,

    FIRST_LEVEL: 1,
    SECOND_LEVEL: 2,
    THIRD_LEVEL: 3
}